### ISSUE TITLE
release_date can be empty

### ISSUE THREAD

**Issue by erantapaa** [pjones/themoviedb#2]
I've noticed that the "release_date" field can be empty and this causes a parse error.
For example, try running the command:

```
tmdb search "fight club"
```

**Comment by pjones** [comment]
I've noticed this too, but I'm too busy to fix this now.  If you have time, please submit a patch.  Thanks.

**Comment by pjones** [comment]
I'm currently cleaning up the code and will fix this.

**Comment by pjones** [comment]
This is fixed in `master`.  Will be released with 1.0.0.0 when I'm done refactoring.
