### ISSUE TITLE
Documentation link not working and docs missing on hackage

### ISSUE THREAD

**Issue by doivosevic** [pjones/themoviedb#4]
https://github.com/pjones/themoviedb/blob/master/Network/API/TheMovieDB.hs is giving me 404
Also, there seems to be documentation missing. I'm not familiar with how to host on hackage so I'm not sure whether it's an automated process or not

**Comment by pjones** [comment]
The problem is in `README.md`.  If you have a chance please fix the issue and send me a PR.  I'll be out of the country until October so I don't think I can get to this right now.

Thanks.
